/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Cliente;
import model.Produto;
import model.Servico;
import model.Tecnico;

/**
 *
 * @author Gabriel Gomes Macedo N6598A4 CC4P33
 */
public class TelaConsultas extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultas
     */
    public TelaConsultas(int telaH) {
        initComponents();
        if(telaH == 1){
            montaTabelaCliente();
        }else if(telaH == 2){
            montaTabelaProduto();
        }else if(telaH == 3){
            montaTabelaTec();
        }else if(telaH == 4){
            montaTabelaServ();
        }
        setLocationRelativeTo(this);
        setResizable(true);
        
    }
    
    private void montaTabelaCliente(){
        tbConsultas.setModel(Cliente.getTableModel());
    }
    
    private void montaTabelaProduto(){
        tbConsultas.setModel(Produto.getTableModel());
    }
    
    private void montaTabelaTec(){
        tbConsultas.setModel(Tecnico.getTableModel());
    }
    
    private void montaTabelaServ(){
        tbConsultas.setModel(Servico.getTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        spTbConsultas = new javax.swing.JScrollPane();
        tbConsultas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas de Itens Cadastrados");

        pnLogo.setBackground(new java.awt.Color(255, 255, 255));
        pnLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        pnLogo.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Consultas");
        pnLogo.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        tbConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbConsultas.setEnabled(false);
        spTbConsultas.setViewportView(tbConsultas);

        pnLogo.add(spTbConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 470));

        getContentPane().add(pnLogo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultas(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JScrollPane spTbConsultas;
    private javax.swing.JTable tbConsultas;
    // End of variables declaration//GEN-END:variables
}
